"""Curated places seed loader.

Reads ``university_seed.yaml`` — the FROZEN, footprint-derived campus geometries
produced by ``geo_context.author_campuses`` — into a ``curated_places``-shaped
GeoDataFrame (kind, name, description, geom in EPSG:4326).
``geo_context.run._run_universities`` loads it into ``world.curated_places``.

Unlike ``landmark_seed.yaml`` (hand-typed WKT points/aliases that flow into
``landmarks``), this file is machine-authored: the WKT is an ST_Union of real
landmark footprints (a MultiPolygon of the actual buildings, not a convex
hull), regenerated by re-running the authoring script and reviewed as a diff.
See agent-compound-docs/decisions/named-place-search.md.
"""

from __future__ import annotations

import logging
from pathlib import Path

import geopandas as gpd
import yaml
from shapely import wkt
from shapely.errors import ShapelyError

logger = logging.getLogger(__name__)

# university_seed.yaml sits at the geo_context package root (one level up).
CURATED_SEED_PATH = Path(__file__).resolve().parent.parent / "university_seed.yaml"
SILVER_SRID = 4326
_DEFAULT_KIND = "university"


def load_curated_frame(path: Path | None = None) -> gpd.GeoDataFrame:
    """Parse the curated seed YAML into a (kind, name, description, geom) frame.

    A row missing name/geometry, or carrying unparseable/empty WKT, is skipped
    with a warning — a single bad row never aborts the load. ``kind`` defaults
    to ``'university'`` (the only curated category today) but is read from the
    row if present, so the table can host other curated kinds later.
    """
    src = path or CURATED_SEED_PATH
    if not src.exists():
        logger.warning("curated seed %s: file missing — nothing to load", src)
        return gpd.GeoDataFrame(
            {
                "kind": [],
                "name": [],
                "description": [],
                "anchor_lat": [],
                "anchor_lon": [],
            },
            geometry=[],
            crs=f"EPSG:{SILVER_SRID}",
        ).rename_geometry("geom")

    raw = yaml.safe_load(src.read_text(encoding="utf-8")) or {}
    rows = raw.get("seeds") or []

    kinds: list[str] = []
    names: list[str] = []
    descriptions: list[str | None] = []
    anchor_lats: list[float | None] = []
    anchor_lons: list[float | None] = []
    geoms: list = []
    for i, row in enumerate(rows):
        name = (row.get("name") or "").strip()
        wkt_str = (row.get("geometry") or "").strip()
        if not (name and wkt_str):
            logger.warning("curated[%d]: missing name/geometry — skipped", i)
            continue
        try:
            geom = wkt.loads(wkt_str)
        except (ShapelyError, ValueError, TypeError):
            logger.warning("curated[%d] %r: unparseable WKT — skipped", i, name)
            continue
        if geom.is_empty:
            logger.warning("curated[%d] %r: empty geometry — skipped", i, name)
            continue
        # Optional [lon, lat] main-building anchor → nullable float columns the
        # named_places view materialises into `anchor_geom`.
        anchor = row.get("anchor")
        if isinstance(anchor, (list, tuple)) and len(anchor) == 2:
            anchor_lons.append(float(anchor[0]))
            anchor_lats.append(float(anchor[1]))
        else:
            anchor_lons.append(None)
            anchor_lats.append(None)
        kinds.append((row.get("kind") or _DEFAULT_KIND).strip())
        names.append(name)
        descriptions.append(row.get("description"))
        geoms.append(geom)

    gdf = gpd.GeoDataFrame(
        {
            "kind": kinds,
            "name": names,
            "description": descriptions,
            "anchor_lat": anchor_lats,
            "anchor_lon": anchor_lons,
        },
        geometry=geoms,
        crs=f"EPSG:{SILVER_SRID}",
    )
    # The PostGIS loader writes the active geometry column; `curated_places.geom`.
    return gdf.rename_geometry("geom")
